src/Entity/Account.php
<?php

namespace App\Entity;

use App\Repository\AccountRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AccountRepository::class)
 */
class Account
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $account_type;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $account_number;

    /**
     * @ORM\Column(type="date")
     */
    private $opening_date;

    /**
     * @ORM\Column(type="float")
     */
    private $account_amount;

    /**
     * @ORM\OneToMany(targetEntity=Operation::class, mappedBy="account", orphanRemoval=true)
     */
    private $operations;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="accounts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function __construct()
    {
        $this->operations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAccountType(): ?string
    {
        return $this->account_type;
    }

    public function setAccountType(string $account_type): self
    {
        $this->account_type = $account_type;

        return $this;
    }

    public function getAccountNumber(): ?string
    {
        return $this->account_number;
    }

    public function setAccountNumber(string $account_number): self
    {
        $this->account_number = $account_number;

        return $this;
    }

    public function getOpeningDate(): ?\DateTimeInterface
    {
        return $this->opening_date;
    }

    public function setOpeningDate(\DateTimeInterface $opening_date): self
    {
        $this->opening_date = $opening_date;

        return $this;
    }

    public function getAccountAmount(): ?float
    {
        return $this->account_amount;
    }

    public function setAccountAmount(float $account_amount): self
    {
        $this->account_amount = $account_amount;

        return $this;
    }

    /**
     * @return Collection|Operation[]
     */
    public function getOperations(): Collection
    {
        return $this->operations;
    }

    public function addOperation(Operation $operation): self
    {
        if (!$this->operations->contains($operation)) {
            $this->operations[] = $operation;
            $operation->setAccount($this);
        }

        return $this;
    }

    public function removeOperation(Operation $operation): self
    {
        if ($this->operations->removeElement($operation)) {
            // set the owning side to null (unless already changed)
            if ($operation->getAccount() === $this) {
                $operation->setAccount(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Operation.php
<?php

namespace App\Entity;

use App\Repository\OperationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OperationRepository::class)
 */
class Operation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $operation_label;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $operation_type;

    /**
     * @ORM\Column(type="float")
     */
    private $operation_amount;

    /**
     * @ORM\Column(type="datetime")
     */
    private $operation_date;

    /**
     * @ORM\ManyToOne(targetEntity=Account::class, inversedBy="operations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $account;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOperationLabel(): ?string
    {
        return $this->operation_label;
    }

    public function setOperationLabel(string $operation_label): self
    {
        $this->operation_label = $operation_label;

        return $this;
    }

    public function getOperationType(): ?string
    {
        return $this->operation_type;
    }

    public function setOperationType(string $operation_type): self
    {
        $this->operation_type = $operation_type;

        return $this;
    }

    public function getOperationAmount(): ?float
    {
        return $this->operation_amount;
    }

    public function setOperationAmount(float $operation_amount): self
    {
        $this->operation_amount = $operation_amount;

        return $this;
    }

    public function getOperationDate(): ?\DateTimeInterface
    {
        return $this->operation_date;
    }

    public function setOperationDate(\DateTimeInterface $operation_date): self
    {
        $this->operation_date = $operation_date;

        return $this;
    }

    public function getAccount(): ?Account
    {
        return $this->account;
    }

    public function setAccount(?Account $account): self
    {
        $this->account = $account;

        return $this;
    }
}

src/Controller/BankController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\User;
use App\Entity\Account;
use App\Entity\Operation;
use App\Form\TransactionType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;


class BankController extends AbstractController
{

    
    /**
     * @Route("/", name="index")
     * @Route("/bank", name="bank")
     */
    public function index(): Response
    {
        return $this->render('bank/index.html.twig', [
            'controller_name' => 'BankController',
        ]);
    }

    /**
     * Require ROLE_USER for only this controller method.
     * @IsGranted("ROLE_USER")
     * 
     * @Route("/accounts", name="accounts")
     */
    public function accounts(): Response
    {
        $user = $this->getUser();
        $accountRepository = $this->getDoctrine()->getRepository(Account::class);
        $accounts = $accountRepository->findBy([
            'user' => $user
        ]);
        dump($accounts);
        // if (!$accounts) {
        //     throw $this->createNotFoundException(
        //         'Vous ne possédez pas encore de compte, cliquez ici pour en créer un (mettre un lien). '
        //     );
        // }
        return $this->render('bank/accounts.html.twig', [
            'accounts' => $accounts,
        ]);
    }

    /**
     * Require ROLE_USER for only this controller method.
     * @IsGranted("ROLE_USER")
     * 
     * @Route("/singleAccount", name="single_account")
     */
    public function singleAccount(): Response
    {
        $accountRepository = $this->getDoctrine()->getRepository(Account::class);
        $singleAccount = $accountRepository->findAll();
        dump($singleAccount);

        $operationRepository = $this->getDoctrine()->getRepository(Operation::class);
        $operations = $operationRepository->findAll();
        dump($operations);

        return $this->render('bank/single_account.html.twig', [
            'singleAccount' =>$singleAccount,
            'operations' => $operations,
        ]);
    }

    /**
     * Require ROLE_USER for only this controller method.
     * @IsGranted("ROLE_USER")
     * 
     * @Route("/addBankAccount", name="add_bank_account")
     */
    public function addBankAccount(): Response
    {
        return $this->render('bank/add_bank_account.html.twig', [
            'controller_name' => 'BankController',
        ]);
    }

    /**
     * Require ROLE_USER for only this controller method.
     * @IsGranted("ROLE_USER")
     * 
     * @Route("/bankTransaction", name="bank_transaction")
     */
    public function bankTransaction(Request $request, ValidatorInterface $validator): Response
    {
        $errors = null;
        $operation = new Operation();
        $form = $this->createForm(TransactionType::class, $operation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // On associe l'opération au compte sélectionné 
            // $operation->setAccount($this->getAccount());
            // On vérifie la présence d'erreur dans l'objet sur la base des règles définies par le  validateur dans l'entité
            $errors = $validator->validate($operation);
            // Si le tableau ne contient pas d'erreurs
            if(count($errors) === 0) {
                $operation->setOperationDate(new \DateTime('now'));
              // On enregistre la nouvelle opération
              $entityManager = $this->getDoctrine()->getManager();
              $entityManager->persist($operation);
              // Attention les requêtes ne sont exécutées que lors du flush donc à ne pas oublier
              $entityManager->flush();
              // On crée des message de succès en session appelés flash messages
              $this->addFlash('success','Votre opération a bien été enregistrée');
              // On redirige la route 
              return $this->redirectToRoute('bank_transaction');
            }

        }

        return $this->render('bank/bank_transaction.html.twig', [
            'form' => $form->createView(),
            'errors' => $errors,

        ]);
    }
        
}

templates/bank/accounts.html.twig
{% extends 'template.html.twig' %}

{% block title %}Vos comptes{% endblock %}

{% block main %}
    <div class="container">
        <h1 class="my-5 text-center">Vos comptes</h1>
        <div class="row">
            {% for account in accounts %}
            {# {% if is_granted('IS_AUTHENTICATED_FULLY') %} #}
                <div class="col-12 col-sm-10 col-md-6 col-lg-4 mb-5">
                    <div class="card text-center">
                        <section class="card-body">
                            <h5 class="card-title">Type de compte : {{account.accountType}}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Numéro de compte : {{account.accountNumber}}</h6>
                            <h6 class="card-subtitle mb-2">Montant du compte :
                            {% if account.AccountAmount > 0 %}
                                <span class="text-success"> + {{account.AccountAmount}} €</span>
                            {% else %}
                                <span class="text-danger"> - {{account.AccountAmount}} €</span>
                            {% endif %}
                            </h6>
                            <hr>
                            {# <ul class="list-group list-group-flush">
                                <li class="list-group-item">Nom & Prénom</li>
                            </ul> #}
                            <a href="#" class="btn btn-primary">Dépot/Retrait</a>
                            <a href="#" class="btn btn-primary">Virement</a>
                            <a href="#" class="btn btn-primary">Cloturer</a>
                            
                            <a href="{{path('single_account', {id:account.id})}}">Voir le compte</a>
                        </section>
                    </div> 
                </div>
            {# {% endif %} #}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/bank/add_bank_account.html.twig
{% extends 'template.html.twig' %}

{% block title %}Créer un compte bancaire{% endblock %}

{% block main %}
<div>
    <h1>Page pour créer un compte bancaire</h1>
</div>

{% endblock %}

templates/bank/bank_transaction.html.twig
{% extends 'template.html.twig' %}

{% block title %}Transaction bancaire{% endblock %}

{% block main %}
<div>
    <h1>Page pour effectuer un dépôt ou un retrait</h1>
</div>

{% for message in app.flashes('success') %}
    <div class="flash-notice alert alert-success" role="alert">
        {{ message }}
    </div>
{% endfor %}

{{ form_start(form) }}
{{ form_row(form.account, {
        label: 'Séléctionnez un compte'
    }) }}
{{ form_row(form.operation_type, {
        label: 'Type d\'opération'
    }) }}
{{ form_row(form.operation_amount, {
        label: 'Montant (en euro)'
    }) }}
{{ form_row(form.operation_label, {
        label: 'Libellé'
    }) }}
<button type="submit" class="btn btn-lg btn-primary mb-3">Envoyer</button>

{{ form_end(form) }}


{% endblock %}

templates/bank/index.html.twig
{% extends 'template.html.twig' %}

{% block title %}Accueil - Banque{% endblock %}

{% block main %}
    <div class="container">
    <h1 class="m-3 text-center">Accueil Inscription/connexion</h1>

        <div class="row m-5 d-flex justify-content-between">
            <div class="card col-md-5 p-0">
                <div class="card-body bg-primary text-white m-0">
                    <h5 class="card-title text-center">Vous connecter</h5>
                </div>
                <div>
                    <p class="card-text p-3">Si vous possédez déjà un compte chez nous, cliquez ici. Vous aurez accès à vos comptes et à la gestion de ceux-ci</p>
                </div>
                <div class="card-body text-center">
                    <a href="{{path("app_login")}}" class="card-link">Connexion</a>
                </div>
            </div>

            <div class="card col-md-5 p-0">
                <div class="card-body bg-primary text-white m-0">
                    <h5 class="card-title text-center">S'inscrire</h5>
                </div>
                <div>
                    <p class="card-text p-3">Vous n'avez pas encore de compte dans notre banque, cliquez ici et découvrez toutes les options qui s'offrent à vous.</p>
                </div>
                <div class="card-body text-center">
                    <a href="{{path("app_register")}}" class="card-link">Inscription</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/bank/single_account.html.twig
{% extends 'template.html.twig' %}

{% block title %}Votre compte{% endblock %}

{% block main %}
<div class="container">
    <h1 class="m-5 text-center">Voir les dernières opérations sur votre compte.</h1>
    <a href="{{path("accounts")}}" class="btn btn-primary my-4">Retour</a>
    {% for singleAccount in singleAccount %}
        <div class="row">
            <div class="col-12 col-sm-10 col-md-6 col-lg-4 mb-5">
                <div class="card text-center">
                    <section class="card-body">
                        <h5 class="card-title">Type de compte : {{singleAccount.accountType}}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Numéro de compte : {{singleAccount.accountNumber}}</h6>
                        <h6 class="card-subtitle mb-2">Montant du compte :
                            {# {% if  > 0 %}
                                <span class="text-success"> + {{account.AccountAmount}} €</span>
                            {% else %}
                                <span class="text-danger"> - {{account.AccountAmount}} €</span>
                            {% endif %} #}
                        </h6>
                        <hr>
                        {# <ul class="list-group list-group-flush">
                            <li class="list-group-item">Nom & Prénom</li>
                        </ul> #}
                        <a href="#" class="btn btn-primary">Dépot/Retrait</a>
                        <a href="#" class="btn btn-primary">Virement</a>
                        <a href="#" class="btn btn-primary">Cloturer</a>
                    </section>
                </div> 
            </div>
        {% endfor %}

        <div class="col-12 col-sm-10 col-md-6 col-lg-8">
        <table class="table">
            <thead class="bg-primary">
                <tr>
                    <th scope="col">Libellé</th>
                    <th scope="col">Montant</th>
                    <th scope="col">Date</th>
                </tr>
            </thead>
            {% for operation in operations %}
                <tbody>
                    <tr>
                    <td>{{operation.operationLabel}}</td>
                    {% if operation.operationType == "+" %}
                        <td class="text-success">{{operation.operationType}}  {{operation.operationAmount}}</td>
                    {% else %}
                        <td class="text-danger">{{operation.operationType}}  {{operation.operationAmount}}</td>
                    {% endif %}
                    <td>{{operation.operationDate|date("m/d/Y H:i:s")}}</td>
                    </tr>
                </tbody>
            {% endfor %}
        </table>
        </div>
    </div>
</div>

{% endblock %}